apiVersion: v1
kind: Service
metadata:
  name: smarketing-frontend-service
  namespace: ${namespace}
  labels:
    app: smarketing-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${export_port}
    protocol: TCP
  selector:
    app: smarketing-frontend